platform :macos, '12.0'

target 'Mistralis' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Mistralis
    pod 'HotKey'
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
end
